version: "3.8"
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      # - ./nginx/nginx.conf:/ng
      # - ./nginx/error.log:/err
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      # - ./nginx/error.log:/var/log/nginx/error.log
    ports:
      - 4000:4000
    depends_on:
      - notes
      - authentication
      - notessearch
  notes:
    image: mhart/alpine-node:14.4.0
    container_name: notes
    command: sh -c "npm install && npm start"
    working_dir: /notes
    volumes:
      - ./notes:/notes
    env_file: 
      - ./notes/docker_compose.env
  authentication:
    image: mhart/alpine-node:14.4.0
    container_name: authentication
    command: sh -c "npm install && npm start"
    working_dir: /authentication
    volumes:
      - ./authentication:/authentication
    env_file: 
      - ./authentication/docker_compose.env
  notessearch:
    image: mhart/alpine-node:14.4.0
    container_name: notessearch
    command: sh -c "npm install && npm start"
    working_dir: /notes_search
    volumes:
      - ./notes_search:/notes_search
    env_file: 
      - ./notes_search/docker_compose.env
  